#O Arquivo sera baseado no SO Debian
FROM debian    
#Nome do Mantenedor
LABEL maintainer 'Igor Rubio'
#Argumento utilizado, que pode ser passado no momento do build do projeto
ARG S3_BUCKET=files
#Este parametro e usado para criar uma variavel de ambiente
ENV S3_BUCKET=${S3_BUCKET}